### ISSUE TITLE
Prüfung, ob zu leerende Tabelle auch existiert, fehlt... (Whoops!)

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/clear_content#10]
Danke für dieses nützliche AddOn, aber leider whoopt es bei Erstbenutzung:
```Error while executing statement "TRUNCATE TABLE rex_article_slice_history"! SQLSTATE[42S02]: Base table or view not found: 1146 Table 'd02b75bd.rex_article_slice_history' doesn't exist```

Lösung des Problems:
Ich habe das PlugIn History vom AddOn Structure kurz installiert, damit existiert die Tabelle - und dann hat es im zweiten Anlauf geklappt. Wäre also cool, wenn du da vorher noch eine Prüfung reinhaust, ob die zu durchrödelnde Tabelle auch existiert.

**Comment by olien** [comment]
Mache ich. Danke sehr!

**Comment by dpf-dd** [comment]
Ich hab mir zu deinem AddOn gestern noch das Löschen von auswählbaren Modulen und Templates hinzugefügt und werde es dir die nächsten Tage per Pull Request zukommen lassen. Das Teil ist echt ausbaufähig :) Auch wenn ich es aktuell nicht brauche, so könnte man z.B. noch Modulaktionen, Medentypen und Meta-Infos "clearen".

Ich könnte mich gut daran gewöhnen, bei neuen Projekten einfach ein gut gepflegtes Redaxo zu duplizieren und dann mit deinem AddOn das Ganze wieder "zu resetten"... :)

**Comment by olien** [comment]
Find ich super...
Möchtest du das AddOn nicht einfach komplett übernehmen?

LG
Oliver
